#cloud-config

packages:
 - nginx

write_files:
- content: |
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
  path: /etc/nginx/snippets/self-signed.conf
- content: |
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers on;
    #ssl_dhparam /etc/nginx/dhparam.pem; 
    ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
    ssl_ecdh_curve secp384r1;
    ssl_session_timeout  10m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;
    # Disable strict transport security for now. You can uncomment the following
    # line if you understand the implications.
    #add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
  path: /etc/nginx/snippets/ssl-params.conf
- content: |
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        include snippets/self-signed.conf;
        include snippets/ssl-params.conf;

        server_name _;

        location / {
          proxy_pass http://localhost:8080/;
          proxy_set_header Host $host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection upgrade;
          proxy_set_header Accept-Encoding gzip;
        }
    }

    server {
        listen 80;
        listen [::]:80;

        server_name _;

        return 301 https://$host$request_uri;
    }
  path: /etc/nginx/sites-available/code-server

runcmd:
  # Update firewall settings.
  # https://docs.oracle.com/en-us/iaas/developer-tutorials/tutorials/apache-on-ubuntu/01oci-ubuntu-apache-summary.htm#set-up-apache-php
  - iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT
  - iptables -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT
  - [ netfilter-persistent, save ]
 
  # Install code-server
  - [su, ubuntu, -c, 'curl -fsSL "https://code-server.dev/install.sh" | sh']
  # Start code-server as a system service
  - [ systemctl, enable, --now, code-server@ubuntu ]

  # Create a Self-Signed SSL Certificate
  - 'openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=AU/ST=Some-State/O=Some Company"'
  # - 'openssl dhparam -out /etc/nginx/dhparam.pem 4096'

  # Enable code server with NGINX
  - [ ln, -s, /etc/nginx/sites-available/code-server, /etc/nginx/sites-enabled/code-server ]
  - [ rm, /etc/nginx/sites-enabled/default ]
  - [ nginx, -t ]
  - [ systemctl, restart, nginx ]